


development:
  adapter: mysql
  username: hacktj
  password: jtkcah
  host: "127.0.0.1"
  database: GavelRank_dev

test:

  database: GavelRank_test


production:

  database: GavelRank_production
  username: GavelRank
  password: <%= ENV['GAVELRANK_DATABASE_PASSWORD'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
