 Event.create("name"=>"TECHMUN","location"=>"TJ High School","teams"=>"Woodson Highschool\nTJ Highschool\nLangley Highschool","best"=>"Woodson Highschool - 5\nThomas Jefferson Highschool - 3\nLangley Highschool - 2","outstanding"=>"Woodson Highschool - 3\nThomas Jefferson Highschool - 1\nLangley Highschool - 4","honorable"=>"Woodson Highschool - 4\nThomas Jefferson Highschool - 0\nLangley Highschool - 6","date"=>"05 May 5, 2015","about"=>"Thomas Jefferson High School for Science and Technology hosts an annual Model United Nations conference attended by hundreds of students from the metro area and beyond.","geo"=>"38.818748,-77.168867","link"=>"https://activities.tjhsst.edu/mun/")
 Event.create("name"=>"ILMUNC","location"=>"University of Pennsylvania","teams"=>"Woodson Highschool\nTJ Highschool\nLangley Highschool","best"=>"Woodson Highschool - 5\nThomas Jefferson Highschool - 3\nLangley Highschool - 2","outstanding"=>"Woodson Highschool - 3\nThomas Jefferson Highschool - 1\nLangley Highschool - 4","honorable"=>"Woodson Highschool - 4\nThomas Jefferson Highschool - 0\nLangley Highschool - 6","date"=>"06 June 16, 2015","about"=>"The Ivy League Model United Nations Conference is the preeminent high school conference hosted annualy at the University of Pennsylvania","geo"=>"39.9522324,-75.1931456", "link"=>"http://www.ilmunc.com/")
 Event.create("name"=>"Virginia Model United Nations(VAMUN)","location"=>"University of Virginia","teams"=>"Woodson Highschool\nTJ Highschool\nLangley Highschool","best"=>"Woodson Highschool - 3\nThomas Jefferson Highschool - 7\nLangley Highschool - 3","outstanding"=>"Woodson Highschool - 7\nThomas Jefferson Highschool - 3\nLangley Highschool - 4","honorable"=>"Woodson Highschool - 9\nThomas Jefferson Highschool - 6\nLangley Highschool - 3","date"=>"11 November 07-09, 2014","geo"=>"38.0350,-78.5050","about"=>"UVA is hosting the thirty-fifith annual Virginia Model UN Conference. VAMUN has given highschool students the chance to problem solve and creation solutions for current real world issues.","link"=>"http://virginia-iro.org/vamun/")
 Event.create("name"=>"William & Mary High School Model United Nations(WMHSMUN)","location"=>"College of William & Mary","teams"=>"Woodson Highschool\nTJ Highschool\nLangley Highschool","best"=>"Woodson Highschool - 7\nThomas Jefferson Highschool - 8\nLangley Highschool - 1","outstanding"=>"Woodson Highschool - 3\nThomas Jefferson Highschool - 4\nLangley Highschool - 6","honorable"=>"Woodson Highschool - 3\nThomas Jefferson Highschool - 8\nLangley Highschool - 7","date"=>"11 November 14-16 2014","geo"=>"37.2711,-76.7075","about"=>"The College of William and Mary is hosing their Twenty-Nineth MUN conference. WMHSMUN has been rated number one in the All-American Model UN's online magazine within the Commonwealth of Virginia","link"=>"http://www.wmhsmun.org/")
 Event.create("name"=>"Prince William Model United Nations","location"=>"C.D. Hylton High School","teams"=>"Woodson Highschool\nTJ Highschool\nLangley Highschool","best"=>"Woodson Highschool - 3\nThomas Jefferson Highschool - 0\nLangley Highschool - 2","outstanding"=>"Woodson Highschool - 9\nThomas Jefferson Highschool - 6\nLangley Highschool - 5","honorable"=>"Woodson Highschool - 5\nThomas Jefferson Highschool - 8\nLangley Highschool - 3","date"=>"12 December 05-06, 2014","geo"=>"38.651197,-77.384883","about"=>"The thirty-first Prince William Model United Nations conference is going to be held at C.D. Hylton HighSchool. It will be an exciting event.","link"=>"https://sites.google.com/site/hyltonmun/")
 Event.create("name"=>"Henrico High School Model United Nations Conference","location"=>"Holman Middle School","teams"=>"Woodson Highschool\nTJ Highschool\nLangley Highschool","best"=>"Woodson Highschool - 2\nThomas Jefferson Highschool - 8\nLangley Highschool - 0","outstanding"=>"Woodson Highschool - 7\nThomas Jefferson Highschool - 0\nLangley Highschool - 9","honorable"=>"Woodson Highschool - 3\nThomas Jefferson Highschool - 0\nLangley Highschool - 6","date"=>"12 December 12-13, 2014","geo"=>"37.6895938,-77.5898247","about"=>"Henrico Highschool is hosting their RichMUNd with the theme this year of Thus do we reach the stars","link"=>"http://richmund.weebly.com/")
 Event.create("name"=>"Chantilly High Model United Nations (CHMUN)","location"=>"Chantilly High School","teams"=>"Woodson Highschool\nTJ Highschool\nLangley Highschool","best"=>"Woodson Highschool - 0\nThomas Jefferson Highschool - 0\nLangley Highschool - 2","outstanding"=>"Woodson Highschool - 5\nThomas Jefferson Highschool - 1\nLangley Highschool - 4","honorable"=>"Woodson Highschool - 4\nThomas Jefferson Highschool - 0\nLangley Highschool - 6","date"=>"01 January 09-10, 2015","geo"=>"38.8803,-77.4065","about"=>"Chantilly High School hosts an annual Model United Nations conference attended by hundreds of students from the metro area and beyond.","link"=>"http://www.chantillymun.org/chmun.php")

 School.create("name"=>"Woodson High School","location"=>"Fairfax, VA","students"=>40,"email"=>"woodson@gmail.com","password"=>"pass","salt"=>"48409","geo"=>"38.840278,-77.275278","score"=>74)
 School.create("name"=>"Thomas Jefferson High School for Science and Technology","location"=>"Alexandria, VA","students"=>200,"email"=>"tj@gmail.com","password"=>"pass","salt"=>"622462","geo"=>"38.818748,-77.168867","score"=>17)
 School.create("name"=>"Langley High School","location"=>"McLean, VA","students"=>120,"email"=>"langley@gmail.com","password"=>"pass","salt"=>"39969","geo"=>"38.949,-77.167","score"=>0)
 
 